$(document).ready(function() {
		$(".q1").click(function(){
			$(".q2").show();
		});
		$(".q2").click(function(){
			$(".q3").show();
		});
		$(".q3").click(function(){
			$(".q4").show();
		});
		$(".q4").click(function(){
			$(".q5").show();
		});
		$(".q5").click(function(){
			$("#submit").show();
		});
		$("#submit").click(function(){
			$(".answer").show();
		});
	});
